on:
  push:
    branches:
      - main

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # scan commits like "feat: add X" or "fix: fix X" to update changelog and bump version
      - name: release-please
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          config-file: .github/release-please.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout repository
        if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/checkout@v2

      - name: setup jdk
        if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: setup gradle and build
        if: ${{ steps.release-please.outputs.release_created }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: upload release
        if: ${{ steps.release-please.outputs.release_created }}
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ steps.release-please.outputs.tag_name }}
          file: '**/build/libs/*'
          file_glob: true
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}